import { randomUUID } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import {
  getProjectTree,
  readProjectFile,
  searchProjectFiles,
  searchProjectText,
  type ProjectFileError
} from "../src/projectFiles.js";

const tempRoots: string[] = [];

function makeTempRoot(): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "agentbridge-files-"));
  tempRoots.push(root);
  return root;
}

function writeText(root: string, relativePath: string, content: string): string {
  const absolutePath = path.join(root, relativePath);
  fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
  fs.writeFileSync(absolutePath, content, "utf8");
  return absolutePath;
}

afterEach(() => {
  for (const root of tempRoots.splice(0)) {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

describe("safe project file browser", () => {
  it("handles randomized tree, search, read, grep, limits, and safety blocks", () => {
    const root = makeTempRoot();
    const suffix = randomUUID().replace(/-/g, "");
    const token = `CODEXLINK_GAMMA_TOKEN_${randomUUID()}`;
    const folder = `folder_${suffix.slice(0, 8)}`;
    const docs = `docs_${suffix.slice(8, 16)}`;
    const nested = `nested_${suffix.slice(16, 24)}`;
    const noteFile = `${folder}/note_${suffix}.txt`;
    const configFile = `${folder}/config_${suffix}.json`;
    const guideFile = `${docs}/guide_${suffix}.md`;
    const targetFile = `${nested}/level1/level2/target_${suffix}.txt`;
    const noteContent = `${token}\nThis file was generated by the randomized gamma test.\n`;

    writeText(root, noteFile, noteContent);
    writeText(root, configFile, JSON.stringify({ token, kind: "config" }, null, 2));
    writeText(root, guideFile, `Guide ${suffix}\n`);
    writeText(root, targetFile, `Nested ${token}\n`);
    writeText(root, "node_modules/fake/ignored.txt", token);
    writeText(root, ".git/ignored.txt", token);
    writeText(root, "dist/ignored.txt", token);
    writeText(root, ".env", `OPENAI_API_KEY=sk-${"a".repeat(24)}\n`);
    writeText(root, ".agentbridge/local_token", "local-token-value-123\n");
    writeText(root, "secret.pem", "-----BEGIN PRIVATE KEY-----\nabc\n-----END PRIVATE KEY-----\n");
    writeText(root, "secret.key", "PRIVATE\n");
    writeText(root, "data.sqlite", "sqlite\n");
    writeText(root, "large.txt", `${"x".repeat(25000)}${token}`);
    const binaryPath = path.join(root, "binary.bin");
    fs.writeFileSync(binaryPath, Buffer.from([0, 1, 2, 3, 4]));

    const tree = getProjectTree(root, { projectId: "GammaProject", maxDepth: 5, maxEntries: 500 });
    expect(tree.entries.map((entry) => entry.path)).toContain(noteFile);
    expect(tree.entries.map((entry) => entry.path)).toContain(targetFile);
    expect(tree.entries.some((entry) => entry.path.includes("node_modules"))).toBe(false);
    expect(tree.entries.some((entry) => entry.path.includes(".git"))).toBe(false);
    expect(tree.entries.some((entry) => entry.path.includes("dist/ignored"))).toBe(false);
    expect(tree.entries.some((entry) => entry.path === ".env")).toBe(false);

    const shallow = getProjectTree(root, { projectId: "GammaProject", maxDepth: 1, maxEntries: 500 });
    expect(shallow.entries.map((entry) => entry.path)).not.toContain(targetFile);
    const tiny = getProjectTree(root, { projectId: "GammaProject", maxDepth: 5, maxEntries: 2 });
    expect(tiny.returned_entries).toBe(2);
    expect(tiny.truncated).toBe(true);

    const fullName = searchProjectFiles(root, { projectId: "GammaProject", query: `note_${suffix}.txt` });
    expect(fullName.matches.map((match) => match.path)).toEqual([noteFile]);
    const partial = searchProjectFiles(root, { projectId: "GammaProject", query: suffix.slice(0, 10) });
    expect(partial.matches.some((match) => match.path === noteFile)).toBe(true);
    expect(partial.matches.some((match) => match.path.includes("node_modules"))).toBe(false);

    const read = readProjectFile(root, { projectId: "GammaProject", relativePath: noteFile });
    expect(read.content).toBe(noteContent);
    expect(read.truncated).toBe(false);
    const windowed = readProjectFile(root, { projectId: "GammaProject", relativePath: noteFile, startLine: 2, numLines: 1 });
    expect(windowed.content).toBe("This file was generated by the randomized gamma test.");

    const grep = searchProjectText(root, { projectId: "GammaProject", query: token });
    expect(grep.matches.map((match) => match.path).sort()).toEqual([configFile, "large.txt", noteFile, targetFile].sort());
    expect(grep.matches.some((match) => match.path.includes("node_modules"))).toBe(false);
    expect(grep.matches.some((match) => match.path.includes(".git"))).toBe(false);
    expect(grep.matches.some((match) => match.path.includes("dist"))).toBe(false);

    const redacted = readProjectFile(root, {
      projectId: "GammaProject",
      relativePath: noteFile,
      maxChars: 50000
    });
    expect(redacted.redacted).toBe(false);
    writeText(root, "safe-secret.txt", `Authorization: Bearer ${"a".repeat(32)}\n`);
    const secretRead = readProjectFile(root, { projectId: "GammaProject", relativePath: "safe-secret.txt" });
    expect(secretRead.content).toContain("Bearer [REDACTED]");
    expect(secretRead.redacted).toBe(true);
    const secretGrep = searchProjectText(root, { projectId: "GammaProject", query: "Authorization" });
    expect(secretGrep.matches[0].snippet).toContain("Bearer [REDACTED]");

    const large = readProjectFile(root, { projectId: "GammaProject", relativePath: "large.txt", maxChars: 20000 });
    expect(large.truncated).toBe(true);
    expect(large.content.length).toBe(20000);

    const hugeContent = `Authorization: Bearer ${"b".repeat(32)}\n${"h".repeat(512 * 1024 + 4096)}`;
    writeText(root, "huge-safe.txt", hugeContent);
    const huge = readProjectFile(root, { projectId: "GammaProject", relativePath: "huge-safe.txt" });
    expect(huge.ok).toBe(true);
    expect(huge.size).toBe(Buffer.byteLength(hugeContent));
    expect(huge.truncated).toBe(true);
    expect(huge.redacted).toBe(true);
    expect(huge.content.length).toBeGreaterThan(0);
    expect(huge.content.length).toBeLessThan(hugeContent.length);
    expect(huge.content).toContain("Bearer [REDACTED]");
    expect(huge.content).not.toContain("b".repeat(32));

    for (const blockedPath of ["../outside.txt", path.join(root, noteFile), "C:\\Windows\\win.ini", "file:///D:/AgentBridge/package.json"]) {
      expect(() => readProjectFile(root, { projectId: "GammaProject", relativePath: blockedPath })).toThrow();
    }
    for (const blockedPath of [".env", ".agentbridge/local_token", "secret.pem", "secret.key", "data.sqlite"]) {
      expect(() => readProjectFile(root, { projectId: "GammaProject", relativePath: blockedPath })).toThrow("blocked");
    }
    try {
      readProjectFile(root, { projectId: "GammaProject", relativePath: "binary.bin" });
      throw new Error("Expected binary read to fail.");
    } catch (error) {
      expect((error as ProjectFileError).code).toBe("binary_file");
    }
  });

  it("redacts sensitive grep query tokens in every returned snippet", () => {
    const root = makeTempRoot();
    const suffix = randomUUID().replace(/-/g, "");
    const token = `CODEXLINK_MANUAL_GREP_${randomUUID()}`;
    const markdownFile = `docs_${suffix}/manual_${suffix}.md`;
    const typeScriptFile = `src_${suffix}/marker_${suffix}.ts`;

    writeText(root, markdownFile, `GREP_TOKEN=${token}\n`);
    writeText(root, typeScriptFile, `export const marker = '${token}';\n`);

    const result = searchProjectText(root, { projectId: "GammaProject", query: token });

    expect(result.redacted).toBe(true);
    expect(result.matches.map((match) => match.path).sort()).toEqual([markdownFile, typeScriptFile].sort());
    for (const match of result.matches) {
      expect(match.snippet).toContain("[REDACTED]");
      expect(match.snippet).not.toContain(token);
    }
  });
});
