import type { AgentBridgeSession, CaptureMode, GitInfo } from "./types.js";

export const generatedNotice = "<!-- Generated by AgentBridge. This file may be replaced by its command. -->";

export function configTemplate(): string {
  return `[auth]
mode = "chatgpt_login"
allow_openai_api_key = false
require_local_approval = true

[server]
host = "127.0.0.1"
port = 7777
expose_public = false

[safety]
redact_secrets = true
require_approval_for_commands = true
require_approval_for_file_write = false
require_approval_for_git_push = true
`;
}

export function userIntentTemplate(): string {
  return `# User Intent

Describe the coding task here.

## Important Notes

- Keep changes focused.
- Do not expose secrets.
`;
}

export function chatGptPlanTemplate(): string {
  return `# ChatGPT Plan

## Goal

Describe the intended outcome.

## Steps

1. Inspect the relevant implementation.
2. Make the minimal focused change.
3. Run the relevant checks.
4. Report changed files, tests, and remaining risks.
`;
}

export function nextActionTemplate(): string {
  return `# Next Action

Run \`agentbridge capture --mode short\`, then fill \`.agentbridge/user_intent.md\` and \`.agentbridge/chatgpt_plan.md\`.
`;
}

export function codexResultTemplate(): string {
  return `# Codex Result

## Summary

Describe what Codex changed.

## Changed Files

- None yet.

## Commands Run

- Not run yet.

## Tests

Not run yet.

## Unresolved Risks

- None listed yet.
`;
}

export function projectContextTemplate(session: AgentBridgeSession, git: GitInfo, mode: CaptureMode): string {
  const diffSection =
    mode === "short"
      ? `## Diff Summary\n\n\`\`\`text\n${git.diffStat}\n\`\`\``
      : `## Diff Summary\n\n\`\`\`text\n${git.diffStat}\n\`\`\`\n\n${git.diff}`;

  return `${generatedNotice}

# Project Context

## Session

- Project: ${session.project_name}
- Root: ${session.project_root}
- Session: ${session.session_id}
- Capture mode: ${mode}
- Status: ${session.status}
- Next action: ${session.next_action}

## Git

- Available: ${git.available ? "yes" : "no"}
- Branch: ${git.branch}
- Changed files: ${git.changedFiles.length}

## Git Status

\`\`\`text
${git.status}
\`\`\`

## Changed Files

${git.changedFiles.length ? git.changedFiles.map((file) => `- ${file}`).join("\n") : "- None"}

${diffSection}

## Recent Commits

\`\`\`text
${git.recentCommits}
\`\`\`

## Risks

- Secret-like values are redacted before this file is written.
- Git data is unavailable if this project is not a git repository.
`;
}

export function codexPromptTemplate(input: {
  sessionGoal?: string;
  userIntent: string;
  projectContext: string;
  chatGptPlan: string;
}): string {
  return `${generatedNotice}

# Task for Codex

## Goal

Use the user intent and ChatGPT plan below to implement the requested coding task.

## Session Goal

${input.sessionGoal?.trim() || "No session goal has been set yet."}

## User Intent

${input.userIntent.trim() || "No user intent has been written yet."}

## Project Context

${input.projectContext.trim() || "No project context has been captured yet."}

## ChatGPT Plan

${input.chatGptPlan.trim() || "No ChatGPT plan has been written yet."}

## Constraints

- Keep changes focused on the stated goal.
- Do not expose secrets.
- Do not rewrite unrelated code.
- Do not run destructive commands without explicit user approval.
- Do not require OpenAI API keys.

## Done When

- The requested change is implemented or clearly blocked.
- Relevant tests or checks are run.
- Any failures are explained.
- Changed files and remaining risks are reported.

## Report Back

Return:

- Summary
- Changed files
- Commands run
- Test result
- Unresolved risks
`;
}

export function chatGptReviewTemplate(input: {
  session: AgentBridgeSession;
  userIntent: string;
  chatGptPlan: string;
  projectContext: string;
  codexResult: string;
}): string {
  return `${generatedNotice}

# ChatGPT Review Packet

## Session Summary

- Project: ${input.session.project_name}
- Root: ${input.session.project_root}
- Status: ${input.session.status}
- Branch: ${input.session.active_branch}
- Next action: ${input.session.next_action}

## User Intent

${input.userIntent.trim() || "No user intent has been written yet."}

## ChatGPT Plan

${input.chatGptPlan.trim() || "No ChatGPT plan has been written yet."}

## Codex Result

${input.codexResult.trim() || "No Codex result has been written yet."}

## Latest Project Context

${input.projectContext.trim() || "No project context has been captured yet."}

## Review Instructions

Review whether Codex satisfied the user intent, whether tests are sufficient, and what the next action should be.
`;
}
